### ISSUE TITLE
Use BoxCast API instead of scraping the web UI

### ISSUE THREAD

**Issue by louis-hildebrand** [recc-tech/tech#268]
To get access to the API, we need to contact customer support. However, using the API would have many benefits compared to using the UI:

* The code (and the tests) would run much more quickly.
* The code would be more reliable - it wouldn't break if BoxCast made some UI changes.
* More features could be added, such as scheduling live broadcasts before the service.

## Tasks

- [x] Update existing code to use the API
- [x] Write automated tests wherever possible (check coverage)
- [x] Remove code that's no longer needed (e.g., the old BoxCast GUI client, the old tests, the logic in the MCR teardown script for getting the broadcast ID, configuration information like the downloads directory)
